apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: certreloader-metrics-monitor
  namespace: certreloader-system
  labels:
    app.kubernetes.io/name: certreloader
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: certreloader
      app.kubernetes.io/component: controller
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
