---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certreloader-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tls.certreloader.io
  resources:
  - tlscertwatches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tls.certreloader.io
  resources:
  - tlscertwatches/finalizers
  verbs:
  - update
- apiGroups:
  - tls.certreloader.io
  resources:
  - tlscertwatches/status
  verbs:
  - get
  - patch
  - update
