apiVersion: v1
kind: ServiceAccount
metadata:
  name: certreloader-controller-manager
  namespace: certreloader-system
  labels:
    app.kubernetes.io/name: certreloader
    app.kubernetes.io/component: controller
